name: Release Go project

on:
  push:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
 build:
    name: GoReleaser build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go Latest
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          replace_existing_draft: true
          replace_existing_artifacts: true
          target_commitish: "{{ .Commit }}"
          tag: "{{ .CurrentTag }}"
          make_latest: true
          mode: append
          name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
          disable: true
          # Upload metadata.json and artifacts.json to the release as well.
          include_meta: true