name: Release Go project

on:
  push:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
 build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go Latest
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: blumbot
          path: dist/*
 create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: blumbot
          path: ./dist
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist/blum-bot_*/*
          tag: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}